name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Download Gradle Wrapper JAR
      run: |
        mkdir -p gradle/wrapper
        curl -L -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v8.2.0/gradle/wrapper/gradle-wrapper.jar
        echo "Gradle wrapper downloaded!"
        ls -la gradle/wrapper/
    
    - name: Fix gradlew permissions and line endings
      run: |
        sed -i 's/\r$//' gradlew || dos2unix gradlew || true
        chmod +x gradlew
        echo "gradlew fixed!"
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: TV-Remote-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
